name: Output and Environment Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest

    
    steps:
      - name: Set output value
        id: set-message
        run: |
          echo "MESSAGE=Hello from job1" >> $GITHUB_OUTPUT

      - name: Set environment variable
        run: |
          echo "MY_ENV_VAR=Environment variable value" >> $GITHUB_ENV

      - name: Use environment variable
        run: |
          echo "${{ env.MY_ENV_VAR }}"

    outputs:
      message: ${{ steps.set-message.outputs.MESSAGE }}

  job2:
    needs: job1
    runs-on: ubuntu-latest
    
    steps:
          
      - name: Use output from job1
        run: |
          echo "${{ needs.job1.outputs.message }}"

  # install_poetry:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: install python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.12"

  #     - name: install poetry
  #       run: |
  #         pipx install poetry
  #         which poetry
  #         poetry --version
