name: Output and Environment Demo

on: push

jobs:
  job1:
    runs-on: ubuntu-latest

    
    steps:
      - name: Set output value
        id: set-message
        run: |
          echo "message=Hello from job1" >> $GITHUB_OUTPUT

      - name: Set environment variable
        run: |
          echo "MY_ENV_VAR=Environment variable value" >> $GITHUB_ENV

      - name: Use environment variable
        run: |
          echo "${{ env.MY_ENV_VAR }}"

    outputs:
      message: ${{ steps.set-message.outputs.message }}

  job2:
    needs: job1
    runs-on: ubuntu-latest
    
    steps:
          
      - name: Use output from job1
        run: |
          echo "${{ needs.job1.outputs.message }}"



      # - name: try env
      # run: |
      #   echo "${{ env.MY_ENV_VAR }}"